In [89]:
import time
import random
from math import *
import operator
import pandas as pd
import numpy as np

In [90]:
# import plotting libraries
import matplotlib
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
%matplotlib inline 

In [91]:
import seaborn as sns
sns.set(style="white", color_codes=True)
sns.set(font_scale=1.5)

In [92]:
# import the ML algorithm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from statsmodels.tools.eval_measures import rmse

In [93]:
# import libraries for metrics and reporting
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn import metrics

In [94]:
df=pd.read_csv('iris.csv')
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [95]:
df['variety'].value_counts()

Setosa        50
Virginica     50
Versicolor    50
Name: variety, dtype: int64

In [100]:
# copy the predictor variables into X and responses in y
X=df[['sepal.length','sepal.width','petal.length','petal.width']]
y=df['variety']

In [101]:
# split the data into training and test data
# for class balance enter stratify=y, [stratify=n does not seem to work]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

In [102]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [103]:
# instantiate the classifier
knn = KNeighborsClassifier(n_neighbors=5)

In [104]:
# fit the training data
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [105]:
# making predictions on the testing set
y_pred = knn.predict(X_test)

In [106]:
y_pred

array(['Versicolor', 'Virginica', 'Setosa', 'Versicolor', 'Setosa',
       'Versicolor', 'Virginica', 'Versicolor', 'Setosa', 'Versicolor',
       'Versicolor', 'Virginica', 'Versicolor', 'Setosa', 'Setosa',
       'Virginica', 'Versicolor', 'Setosa', 'Setosa', 'Setosa',
       'Virginica', 'Virginica', 'Virginica', 'Setosa', 'Versicolor',
       'Setosa', 'Versicolor', 'Versicolor', 'Versicolor', 'Virginica',
       'Versicolor', 'Versicolor', 'Virginica', 'Virginica', 'Virginica',
       'Setosa', 'Virginica', 'Virginica', 'Virginica', 'Virginica',
       'Setosa', 'Setosa', 'Versicolor', 'Setosa', 'Versicolor'],
      dtype=object)

In [107]:
#confusion_matrix
metrics.confusion_matrix(y_test, y_pred)

array([[14,  0,  0],
       [ 0, 16,  1],
       [ 0,  0, 14]], dtype=int64)

In [30]:
# comparing actual response values (y_test) with predicted response values (y_pred)
print("kNN model accuracy:", metrics.accuracy_score(y_test, y_pred))

kNN model accuracy: 0.9777777777777777


In [31]:
# ['sepal_length','sepal_width', 'petal_length', 'petal_width']]
# making prediction for out of sample data
sample = [[3, 5, 4, 2]]

preds = knn.predict(sample)
preds

array(['Versicolor'], dtype=object)

In [32]:
# comparing actual response values (y_test) with predicted response values (y_pred)
print("kNN model accuracy:\n", metrics.classification_report(y_test, y_pred))

kNN model accuracy:
               precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        14
  Versicolor       1.00      0.94      0.97        17
   Virginica       0.93      1.00      0.97        14

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [33]:
metrics.f1_score(y_test, y_pred, average='weighted')

0.9778242192035296

In [34]:
# find the difference between the sets
set(y_test) - set(y_pred)

set()

In [35]:
x=(knn.predict_proba(X_test))

In [45]:
inputarray = ['4.5', '3.1', '2.9', '5.1']
exp_measure=np.array(inputarray)
exp_measure.shape

(4,)

In [47]:
exp_measure1=exp_measure.reshape(1, len(exp_measure))
exp_measure1.shape

(1, 4)

In [61]:
x = np.array(df.drop(['variety'],1))

In [63]:
y = np.array(df['variety'])

In [64]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.10)

In [65]:
clf = KNeighborsClassifier()

In [66]:
clf.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [67]:
accuracy = clf.score(x_test, y_test)

In [68]:
print(accuracy)

0.9333333333333333


In [69]:
clf.predict(exp_measure1)

C:\Users\bheru\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:171: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')
C:\Users\bheru\anaconda3\lib\site-packages\sklearn\neighbors\_base.py:604: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  X = check_array(X, accept_sparse='csr')


array(['Virginica'], dtype=object)

###### Tree tuning

In [108]:
knn = KNeighborsClassifier(n_neighbors=5, algorithm='kd_tree', leaf_size=10)

In [109]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='kd_tree', leaf_size=10, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [110]:
print(metrics.confusion_matrix(y_test, y_pred))
print("kNN model accuracy:", metrics.accuracy_score(y_test, y_pred))

[[14  0  0]
 [ 0 16  1]
 [ 0  0 14]]
kNN model accuracy: 0.9777777777777777


In [111]:
# print the neighbors
knn.kneighbors([[1, 2,3, 5]], n_neighbors=5)

(array([[5.34789678, 5.60892146, 5.67274184, 5.68066897, 5.86600375]]),
 array([[17, 68, 64, 18,  3]], dtype=int64))